###запрос на вход, получаем куки
GET http://127.0.0.1:1080/login/Roman

###если есть куки открываем чат
GET http://127.0.0.1:1080/chat/
###

POST http://127.0.0.1:1080/send/
Content-Type: application/json

{
"Message": "ssdfsdf"
}
###